services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mobile_order_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mobile_order_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mobile_order_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mobile_order
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: mobile_order_user
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mobile_order_network

  nginx:
    image: nginx:alpine
    container_name: mobile_order_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mobile_order_network
    depends_on:
      - app

volumes:
  db_data:
    driver: local

networks:
  mobile_order_network:
    driver: bridge

